name: chess_engines
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9  ## specify desired version
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tensorflow-deps
  - jupyterlab
  - ipykernel

  ## PyPI packages
  - pip:
    - tensorflow-macos
    - tensorflow-metal  
    - python-chess

